#URL
baseURL=https://practice.expandtesting.com/login
demoQa=https://demoqa.com/

#Credentials 
practiceUsername=practice
practiceUserPassword=SuperSecretPassword!

#UserDetails
demoQA_fullName=Prabha
demoQA_Email=test@gmail.com
demoQa_Address=testing address